### ISSUE TITLE
Cannot tap ryan-robeson/gimp

### ISSUE THREAD

**Issue by guidota** [ryan-robeson/homebrew-gimp#4]
Hi! 
Already tried `brew update-reset` but everything seems to be ok.

$ brew tap ryan-robeson/gimp --debug
```
==> Tapping as full clone
==> Tapping ryan-robeson/gimp
Cloning into '/usr/local/Homebrew/Library/Taps/ryan-robeson/homebrew-gimp'...
remote: Enumerating objects: 40, done.
remote: Counting objects: 100% (40/40), done.
remote: Compressing objects: 100% (25/25), done.
remote: Total 122 (delta 19), reused 33 (delta 14), pack-reused 82
Receiving objects: 100% (122/122), 50.54 KiB | 442.00 KiB/s, done.
Resolving deltas: 100% (60/60), done.
Error: Non-file alias: /usr/local/Homebrew/Library/Taps/ryan-robeson/homebrew-gimp/Aliases/libgimp2.0
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FromPathLoader): loading /usr/local/Homebrew/Library/Taps/ryan-robeson/homebrew-gimp/Formula/pygtk.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FromPathLoader): loading /usr/local/Homebrew/Library/Taps/ryan-robeson/homebrew-gimp/Formula/gegl-gimp.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FromPathLoader): loading /usr/local/Homebrew/Library/Taps/ryan-robeson/homebrew-gimp/Formula/resynthesizer@2.10.18.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FromPathLoader): loading /usr/local/Homebrew/Library/Taps/ryan-robeson/homebrew-gimp/Formula/libgimp2.0@2.10.10.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FromPathLoader): loading /usr/local/Homebrew/Library/Taps/ryan-robeson/homebrew-gimp/Formula/mypaint-brushes.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FromPathLoader): loading /usr/local/Homebrew/Library/Taps/ryan-robeson/homebrew-gimp/Formula/libgimp2.0@2.10.14.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FromPathLoader): loading /usr/local/Homebrew/Library/Taps/ryan-robeson/homebrew-gimp/Formula/python@2.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FromPathLoader): loading /usr/local/Homebrew/Library/Taps/ryan-robeson/homebrew-gimp/Formula/resynthesizer.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FromPathLoader): loading /usr/local/Homebrew/Library/Taps/ryan-robeson/homebrew-gimp/Formula/resynthesizer@2.10.14.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FromPathLoader): loading /usr/local/Homebrew/Library/Taps/ryan-robeson/homebrew-gimp/Formula/resynthesizer@2.10.10.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FromPathLoader): loading /usr/local/Homebrew/Library/Taps/ryan-robeson/homebrew-gimp/Formula/libgimp2.0@2.10.18.rb
/usr/local/Homebrew/Library/Homebrew/brew.rb (Formulary::FromPathLoader): loading /usr/local/Homebrew/Library/Taps/ryan-robeson/homebrew-gimp/Formula/pygobject.rb
Error: Cannot tap ryan-robeson/gimp: invalid syntax in tap!
/usr/local/Homebrew/Library/Homebrew/tap.rb:275:in `install'
/usr/local/Homebrew/Library/Homebrew/cmd/tap.rb:65:in `tap'
/usr/local/Homebrew/Library/Homebrew/brew.rb:111:in `<main>'
```

**Comment by ryan-robeson** [comment]
Hi, thanks for reaching out.

Just added a commit that I believe will fix this. Please try again and let me know what happens.

Thanks!

**Comment by guidota** [comment]
Fixed! Thanks 🚀
